name: Docker Image CI

on:
  # listen master branch
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    #  dùng để trỏ tới repo chính xác( dùng trong trường hợp repo có nhiều project)
    # defaults:
    #   run:
    #     working-directory: ./your-path

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: echo "${{ secrets.TWITTER_ENV_DEVELOPMENT }}" > .env.development
      - name: Build the Docker image
        # Nếu build production thì remove -f Dockerfile.dev
        run: docker build --progress=plain -t hoangquyen99/twitter:v4 -f Dockerfile.dev .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push hoangquyen99/twitter:v4
